--- 
title: "Introduction to spatial-temporal data anlysis using R"
author: "Tsubasa Yamaguchi"
date: "`r Sys.Date()`"
output: 
  bookdown::gitbook:
    split_by: rmd  
    split_bib: yes  
    number_sections: true   
    toc_depth: 4 
    css: custom_style.css   
    df_print: paged
site: bookdown::bookdown_site  
output_dir: "docs"  
documentclass: book  
header-includes:
   - \usepackage{amsmath}
   - \usepackage{nccmath}
biblio-style: jecon    
bibliography: Spatiotemporal.bib   
link-citations: yes
csl: primates.csl
---

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE, fig.align = "center",
                      cache = TRUE)

Sys.setenv("plotly_username"="Tsubasa_Yamaguchi")
Sys.setenv("plotly_api_key"="FyXiPMTRDyqnDETur1lG")
```

# 本稿の目的 {-}   
本稿は、**一般化加法モデル(GAM)**の概要を解説し、それをRで実行する方法を学ぶことを目的とする。本稿の内容は[こちら](https://tsubasayamaguchi-jinrui.github.io/GAM_nyuumon/)から読むことができる。  

GAMは一般化線形モデル(GLMに代表される線形なモデルを拡張し、変数間の関係をより柔軟な形で表現できるようにしたものである。そのため、**GLMで仮定されるような単調増加または単調減少の関係だけでなく、非線形な関係を調べることができる**。  

霊長類の行動のような複雑なデータでは変数間の関係が非線形になることがしばしばあるため、GAMは多くの研究で用いられている[e.g., @Matsumoto2017; @Taniguchi2018; @Hongo2022]。GLMのように線形性を仮定するモデルがデータに当てはまらない場合には、GAMなどの非線形性を許容するモデルを使用する必要性が生じてくるだろう。  

本稿は、Alain Zuurが執筆した"A beginner's guide to generalized additive models with R"[@Zuur2012]の内容を基に執筆している。本書はなるべく数学的な説明を省きつつ、実際の生態学のデータを用いてGAMについてわかりやすく解説したもので、GAMの入門として非常によい書籍である。より詳細な情報を知りたい場合は原著にアクセスしていただきたい。  

その他に参考にしたのは以下の本である。  

- @Zuur2009 Mixed effects models and extensions in ecology with R. 
- @James2013 An Introduction to Statistical Learning with Applications in R.  
- @Takezawa2009 Rによるノンパラメトリック回帰の入門講義  
